<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1599563073422' stop='1599563160072'>
    <name>Jetpack pre-connection</name>
    <title>Jetpack pre-connection</title>
    <test-cases>
        <test-case start='1599563076706' status='failed' stop='1599563104268'>
            <name>Can find connect button on plugins page</name>
            <title>Can find connect button on plugins page</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Test failed: Jetpack pre-connection :: Can find connect button on plugins page' source='dcd5675e-10fa-4221-a04a-f8acfce7ada8-attachment.png' type='image/png' size='32655'/>
            </attachments>
            <failure>
                <message>TypeError [ERR_INVALID_URL]: Invalid URL: null</message>
                <stack-trace>TypeError [ERR_INVALID_URL]: Invalid URL: null
                    at onParseError (internal/url.js:241:17)
                    at new URL (internal/url.js:319:5)
                    at _callee5$ (/home/travis/build/Automattic/jetpack/tests/e2e/lib/flows/jetpack-connect.js:125:15)
                    at tryCatch (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.(anonymous function) [as next] (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
                    at /home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
                    at new Promise (&lt;anonymous>)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1599563104268' status='failed' stop='1599563131826'>
            <name>Can find connect button on dashboard page</name>
            <title>Can find connect button on dashboard page</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Test failed: Jetpack pre-connection :: Can find connect button on dashboard page' source='28936c83-ea08-49e1-b292-18091ef6b837-attachment.png' type='image/png' size='32655'/>
            </attachments>
            <failure>
                <message>TypeError [ERR_INVALID_URL]: Invalid URL: null</message>
                <stack-trace>TypeError [ERR_INVALID_URL]: Invalid URL: null
                    at onParseError (internal/url.js:241:17)
                    at new URL (internal/url.js:319:5)
                    at _callee5$ (/home/travis/build/Automattic/jetpack/tests/e2e/lib/flows/jetpack-connect.js:125:15)
                    at tryCatch (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.(anonymous function) [as next] (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
                    at /home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
                    at new Promise (&lt;anonymous>)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1599563131826' status='failed' stop='1599563159288'>
            <name>Can find connect button on Jetpack page</name>
            <title>Can find connect button on Jetpack page</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Test failed: Jetpack pre-connection :: Can find connect button on Jetpack page' source='70cf38e6-e0c5-4f64-b758-6ad860dd97b8-attachment.png' type='image/png' size='32655'/>
            </attachments>
            <failure>
                <message>TypeError [ERR_INVALID_URL]: Invalid URL: null</message>
                <stack-trace>TypeError [ERR_INVALID_URL]: Invalid URL: null
                    at onParseError (internal/url.js:241:17)
                    at new URL (internal/url.js:319:5)
                    at _callee5$ (/home/travis/build/Automattic/jetpack/tests/e2e/lib/flows/jetpack-connect.js:125:15)
                    at tryCatch (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.(anonymous function) [as next] (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
                    at /home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
                    at new Promise (&lt;anonymous>)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>