<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1599563976919' stop='1599564064179'>
    <name>Jetpack pre-connection</name>
    <title>Jetpack pre-connection</title>
    <test-cases>
        <test-case start='1599563980392' status='failed' stop='1599564008021'>
            <name>Can find connect button on plugins page</name>
            <title>Can find connect button on plugins page</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Test failed: Jetpack pre-connection :: Can find connect button on plugins page' source='874fca5e-9c4c-4214-983d-8c5eac529e35-attachment.png' type='image/png' size='32655'/>
            </attachments>
            <failure>
                <message>TypeError [ERR_INVALID_URL]: Invalid URL: null</message>
                <stack-trace>TypeError [ERR_INVALID_URL]: Invalid URL: null
                    at onParseError (internal/url.js:241:17)
                    at new URL (internal/url.js:319:5)
                    at _callee5$ (/home/travis/build/Automattic/jetpack/tests/e2e/lib/flows/jetpack-connect.js:125:15)
                    at tryCatch (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.(anonymous function) [as next] (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
                    at /home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
                    at new Promise (&lt;anonymous>)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1599564008021' status='failed' stop='1599564035675'>
            <name>Can find connect button on dashboard page</name>
            <title>Can find connect button on dashboard page</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Test failed: Jetpack pre-connection :: Can find connect button on dashboard page' source='afb4aad1-d5ca-4f76-9171-7c60fee785da-attachment.png' type='image/png' size='32655'/>
            </attachments>
            <failure>
                <message>TypeError [ERR_INVALID_URL]: Invalid URL: null</message>
                <stack-trace>TypeError [ERR_INVALID_URL]: Invalid URL: null
                    at onParseError (internal/url.js:241:17)
                    at new URL (internal/url.js:319:5)
                    at _callee5$ (/home/travis/build/Automattic/jetpack/tests/e2e/lib/flows/jetpack-connect.js:125:15)
                    at tryCatch (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.(anonymous function) [as next] (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
                    at /home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
                    at new Promise (&lt;anonymous>)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1599564035675' status='failed' stop='1599564063380'>
            <name>Can find connect button on Jetpack page</name>
            <title>Can find connect button on Jetpack page</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Test failed: Jetpack pre-connection :: Can find connect button on Jetpack page' source='daaac4eb-6301-407c-a662-8809164a05e5-attachment.png' type='image/png' size='32655'/>
            </attachments>
            <failure>
                <message>TypeError [ERR_INVALID_URL]: Invalid URL: null</message>
                <stack-trace>TypeError [ERR_INVALID_URL]: Invalid URL: null
                    at onParseError (internal/url.js:241:17)
                    at new URL (internal/url.js:319:5)
                    at _callee5$ (/home/travis/build/Automattic/jetpack/tests/e2e/lib/flows/jetpack-connect.js:125:15)
                    at tryCatch (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.(anonymous function) [as next] (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
                    at /home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
                    at new Promise (&lt;anonymous>)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>