<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1606803987071' stop='1606804062435'>
    <name>Jetpack updater</name>
    <title>Jetpack updater</title>
    <test-cases>
        <test-case start='1606804000511' status='failed' stop='1606804030212'>
            <name>Plugin updater</name>
            <title>Plugin updater</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1606804000512' status='undefined'>
                    <name>Can login and navigate to Plugins page</name>
                    <title>Can login and navigate to Plugins page</title>
                    <attachments>
                        <attachment title='Test failed: Jetpack updater :: Plugin updater' source='ad360536-7fc8-4c34-81b9-239961a38727-attachment.png' type='image/png' size='4214'/>
                    </attachments>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Error: Timeout - Async callback was not invoked within the 300000 ms timeout specified by jest.setTimeout.</message>
                <stack-trace>Timeout - Async callback was not invoked within the 300000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 300000 ms timeout specified by jest.setTimeout.
                    at mapper (/home/runner/work/jetpack/jetpack/node_modules/jest-config/node_modules/jest-jasmine2/build/queueRunner.js:27:45)
                    at /home/runner/work/jetpack/jetpack/node_modules/jest-config/node_modules/jest-jasmine2/build/queueRunner.js:75:41
                    at runMicrotasks (&lt;anonymous>)
                    at processTicksAndRejections (internal/process/task_queues.js:97:5)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>