<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1610173521657' stop='1610173674151'>
    <name>Jetpack updater</name>
    <title>Jetpack updater</title>
    <test-cases>
        <test-case start='1610173542757' status='failed' stop='1610173638191'>
            <name>Plugin updater</name>
            <title>Plugin updater</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1610173542758' status='passed' stop='1610173545402'>
                    <name>Can login and navigate to Plugins page</name>
                    <title>Can login and navigate to Plugins page</title>
                    <attachments/>
                    <steps/>
                </step>
                <step start='1610173545402' status='passed' stop='1610173550842'>
                    <name>Can update Jetpack</name>
                    <title>Can update Jetpack</title>
                    <attachments/>
                    <steps/>
                </step>
                <step start='1610173550842' status='undefined'>
                    <name>Can connect Jetpack</name>
                    <title>Can connect Jetpack</title>
                    <attachments>
                        <attachment title='Test failed: Jetpack updater :: Plugin updater' source='86e3b1e9-03c1-40f4-b9a1-f20e854ea98d-attachment.png' type='image/png' size='279724'/>
                    </attachments>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Error: Site does not have free plan</message>
                <stack-trace>Error: Site does not have free plan
                    at _callee4$ (/home/runner/work/jetpack/jetpack/tests/e2e/lib/flows/jetpack-connect.js:109:9)
                    at tryCatch (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.&lt;computed> [as next] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>