<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1610623946974' stop='1610623982988'>
    <name>Connection</name>
    <title>Connection</title>
    <test-cases>
        <test-case start='1610623950866' status='failed' stop='1610623979587'>
            <name>In-place</name>
            <title>In-place</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1610623950867' status='undefined'>
                    <name>Can start in-place connection</name>
                    <title>Can start in-place connection</title>
                    <attachments>
                        <attachment title='Test failed: Connection :: In-place' source='4300019e-53fb-41bd-92a5-cf096a16a485-attachment.png' type='image/png' size='4214'/>
                    </attachments>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Error: Timeout - Async callback was not invoked within the 300000 ms timeout specified by jest.setTimeout.</message>
                <stack-trace>Timeout - Async callback was not invoked within the 300000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 300000 ms timeout specified by jest.setTimeout.
                    at mapper (/home/runner/work/jetpack/jetpack/node_modules/jest-config/node_modules/jest-jasmine2/build/queueRunner.js:27:45)
                    at /home/runner/work/jetpack/jetpack/node_modules/jest-config/node_modules/jest-jasmine2/build/queueRunner.js:75:41
                    at runMicrotasks (&lt;anonymous>)
                    at processTicksAndRejections (internal/process/task_queues.js:97:5)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>